blueprint:
  name: AC Filter Life Tracker
  description: Track AC runtime in all modes except 'off' and update a timer.
  domain: automation
  input:
    ac_entity:
      name: AC Entity
      description: Your climate device (AC).
      selector:
        entity:
          domain: climate
    runtime_timer:
      name: Runtime Timer
      description: The timer that tracks AC runtime in 1-minute intervals.
      selector:
        entity:
          domain: timer

mode: single

trigger:
  - platform: state
    entity_id: !input ac_entity

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state != 'off' }}"
        sequence:
          - service: timer.start
            target:
              entity_id: !input runtime_timer

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: timer.cancel
            target:
              entity_id: !input runtime_timer
