blueprint:
  name: AC Filter Life Tracker v1.2
  description: >
    Tracks AC filter life in minutes. Decreases filter life by 1 each minute
    when AC is on (any state except 'off').
  domain: automation
  input:
    climate_entity:
      name: AC Climate Entity
      description: The climate entity representing the AC
      selector:
        entity:
          domain: climate
    filter_life_input:
      name: Filter Life Input Number
      description: The input_number that tracks remaining filter life (in minutes)
      selector:
        entity:
          domain: input_number

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: state
    entity_id: !input climate_entity
    state_not: "off"
  - condition: numeric_state
    entity_id: !input filter_life_input
    above: 0

action:
  - service: input_number.set_value
    data:
      value: >
        {% set current = states(input.filter_life_input) | int %}
        {{ current - 1 }}
    target:
      entity_id: !input filter_life_input

mode: single
