blueprint:
  name: Control Multiple ACs v1.1
  description: Set HVAC mode and temperature on multiple climate devices
  domain: script
  input:
    ac_targets:
      name: AC Units
      description: Choose the climate entities (ACs) to control
      selector:
        target:
          entity:
            domain: climate

    hvac_mode:
      name: HVAC Mode
      description: Mode to set for the ACs
      default: cool
      selector:
        select:
          options:
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
            - "off"

    target_temp:
      name: Target Temperature
      description: Desired temperature to set
      default: 24
      selector:
        number:
          min: 16
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

mode: single
sequence:
  - service: climate.set_temperature
    target: !input ac_targets
    data:
      hvac_mode: !input hvac_mode
      temperature: !input target_temp
