blueprint:
  name: Control Multiple ACs v1.7
  description: Set HVAC mode and temperature for selected AC units
  domain: script
  input:
    ac_targets:
      name: AC Units
      description: Select the AC devices to control
      selector:
        target:
          entity:
            domain: climate

    hvac_mode:
      name: HVAC Mode
      description: Mode to set for the ACs
      default: cool
      selector:
        select:
          options:
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
            - "off"

    target_temp:
      name: Temperature (optional)
      description: Leave empty to keep the current temperature
      default:
      selector:
        number:
          min: 16
          max: 30
          step: 1
          mode: box
          unit_of_measurement: "°C"

mode: single
sequence:
  - service: climate.set_hvac_mode
    target: !input ac_targets
    data:
      hvac_mode: !input hvac_mode

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ target_temp is defined and target_temp is not none }}
        sequence:
          - service: climate.set_temperature
            target: !input ac_targets
            data:
              temperature: "{{ target_temp | float }}"
