blueprint:
  name: Control Multiple ACs v1.3
  description: Set HVAC mode and whole-number temperature on selected AC units
  domain: script
  input:
    ac_targets:
      name: AC Units
      description: Select the climate devices (ACs) to control
      selector:
        target:
          entity:
            domain: climate

    hvac_mode:
      name: HVAC Mode
      description: Mode to set for the ACs
      default: cool
      selector:
        select:
          options:
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
            - "off"

    target_temp:
      name: Temperature
      description: Temperature to set (°C)
      default: 24
      selector:
        number:
          min: 16
          max: 30
          step: 1
          unit_of_measurement: "°C"

mode: single
sequence:
  - service: climate.set_hvac_mode
    target: !input ac_targets
    data:
      hvac_mode: !input hvac_mode

  - service: climate.set_temperature
    target: !input ac_targets
    data:
      temperature: !input target_temp
