blueprint:
  name: Control Multiple ACs v1.8
  description: Set HVAC mode and/or temperature for selected AC units
  domain: automation
  input:
    ac_targets:
      name: AC Units
      description: Select the AC devices to control
      selector:
        target:
          entity:
            domain: climate

    hvac_mode:
      name: HVAC Mode (optional)
      description: Leave empty to keep current mode
      default:
      selector:
        select:
          options:
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
            - "off"
          custom_value: false
          mode: dropdown

    target_temp:
      name: Temperature (optional)
      description: Leave empty to keep the current temperature
      default:
      selector:
        number:
          min: 16
          max: 30
          step: 1
          mode: box
          unit_of_measurement: "°C"

trigger:
  - platform: event
    event_type: automation_trigger

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ hvac_mode is defined and hvac_mode is not none and hvac_mode != '' }}
        sequence:
          - service: climate.set_hvac_mode
            target: !input ac_targets
            data:
              hvac_mode: !input hvac_mode

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ target_temp is defined and target_temp is not none and target_temp != '' }}
        sequence:
          - service: climate.set_temperature
            target: !input ac_targets
            data:
              temperature: "{{ target_temp | float }}"
mode: single
