blueprint:
  name: Control Multiple ACs v1.0
  description: Set mode and temperature for selected ACs
  domain: script
  input:
    ac_targets:
      name: AC Units
      description: Select the ACs you want to control
      selector:
        target:
          entity:
            domain: climate

    hvac_mode:
      name: Mode
      description: HVAC mode to set (e.g. cool, heat, auto)
      default: cool
      selector:
        select:
          options:
            - auto
            - cool
            - heat
            - dry
            - fan_only
            - "off"

    target_temp:
      name: Temperature
      description: Target temperature
      default: 24
      selector:
        number:
          min: 16
          max: 30
          step: 0.5
          unit_of_measurement: °C

mode: single
sequence:
  - service: climate.set_temperature
    data:
      hvac_mode: !input hvac_mode
      temperature: !input target_temp
    target: !input ac_targets
