blueprint:
  name: Light Control by Door Sensor
  description: >
    Turn a light on when the door opens and turn it off when the door closes.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      description: Binary sensor that detects door open/close state
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Light
      description: The light to control
      selector:
        entity:
          domain: light

trigger:
  - platform: state
    entity_id: !input door_sensor
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input door_sensor
    from: 'on'
    to: 'off'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: 'on'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: 'off'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity

mode: restart
