blueprint:
  name: Light or Switch Control by Door Sensor
  description: >
    Turn a light or switch ON when the door opens and OFF when the door closes.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      description: Binary sensor that detects door open/close state
      selector:
        entity:
          domain: binary_sensor
    target_entity:
      name: Light or Switch
      description: Light or switch to control
      selector:
        entity:
          filter:
            - domain: light
            - domain: switch

trigger:
  - platform: state
    entity_id: !input door_sensor
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input door_sensor
    from: 'on'
    to: 'off'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: 'on'
        sequence:
          - service: >
              {% if target_entity.startswith('light.') %}
                light.turn_on
              {% elif target_entity.startswith('switch.') %}
                switch.turn_on
              {% else %}
                homeassistant.turn_on
              {% endif %}
            data:
              entity_id: !input target_entity

      - conditions:
          - condition: state
            entity_id: !input door_sensor
            state: 'off'
        sequence:
          - service: >
              {% if target_entity.startswith('light.') %}
                light.turn_off
              {% elif target_entity.startswith('switch.') %}
                switch.turn_off
              {% else %}
                homeassistant.turn_off
              {% endif %}
            data:
              entity_id: !input target_entity

mode: restart
