blueprint:
  name: Light or Switch Control by Door Sensor
  description: >
    Turns a light or switch ON when the door is opened, OFF when closed.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
    target_entity:
      name: Light or Switch
      selector:
        entity:
          filter:
            - domain: light
            - domain: switch

trigger:
  - platform: state
    entity_id: !input door_sensor

action:
  - variables:
      target: !input target_entity
      domain: "{{ target.split('.')[0] }}"
      service: "{{ domain }}.turn_{{ 'on' if trigger.to_state.state == 'on' else 'off' }}"
  - service: "{{ service }}"
    target:
      entity_id: "{{ target }}"

mode: restart
