blueprint:
  name: Sync heater temperature with AC mode v1.5
  description: >
    Sets heater temperature based on AC mode.
    Heat -> 30°C, Cool -> 5°C.
    Works with multiple heaters.
    Runs only if at least one heater needs change.
    Supports extra actions per mode.
    Triggered when AC turns on or mode changes.
  domain: automation

  input:
    ac_entity:
      name: AC device
      selector:
        entity:
          domain: climate

    heater_entities:
      name: Heater devices
      selector:
        entity:
          domain: climate
          multiple: true

    heat_action:
      name: Extra action on HEAT
      default: []
      selector:
        action: {}

    cool_action:
      name: Extra action on COOL
      default: []
      selector:
        action: {}

trigger:
  # Trigger on any state change (off <-> on) or hvac_mode change
  - platform: state
    entity_id: !input ac_entity
  - platform: state
    entity_id: !input ac_entity
    attribute: hvac_mode

variables:
  ac: !input ac_entity
  heaters: !input heater_entities
  target_temp: >
    {% if is_state(ac, 'heat') %}
      30
    {% elif is_state(ac, 'cool') %}
      5
    {% else %}
      none
    {% endif %}

  heaters_to_update: >
    {% set result = [] %}
    {% for h in heaters %}
      {% set current = state_attr(h, 'temperature') | float(0) %}
      {% if target_temp != none and current != target_temp %}
        {% set result = result + [h] %}
      {% endif %}
    {% endfor %}
    {{ result }}

condition:
  # Only continue if at least one heater needs an update
  - condition: template
    value_template: "{{ heaters_to_update | length > 0 }}"

action:
  # Set the target temperature on all heaters that need update
  - service: climate.set_temperature
    target:
      entity_id: "{{ heaters_to_update }}"
    data:
      temperature: "{{ target_temp }}"

  # Run optional per-mode actions
  - choose:
      - conditions:
          - condition: state
            entity_id: !input ac_entity
            state: "heat"
        sequence: !input heat_action

      - conditions:
          - condition: state
            entity_id: !input ac_entity
            state: "cool"
        sequence: !input cool_action
