blueprint:
  name: Sync heater temperature with AC mode
  description: >
    Sets heater temperature based on AC mode.
    Heat -> 30°C, Cool -> 5°C.
    Works with multiple heaters.
    Runs only if at least one heater needs change.
    Optionally runs extra actions.
  domain: automation

  input:
    ac_entity:
      name: AC device
      selector:
        entity:
          domain: climate

    heater_entities:
      name: Heater devices
      selector:
        entity:
          domain: climate
          multiple: true

    extra_action:
      name: Optional extra action
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input ac_entity
    attribute: hvac_mode

variables:
  ac: !input ac_entity
  heaters: !input heater_entities
  target_temp: >
    {% if is_state(ac, 'heat') %}
      30
    {% elif is_state(ac, 'cool') %}
      5
    {% else %}
      none
    {% endif %}

  heaters_to_update: >
    {% set result = [] %}
    {% for h in heaters %}
      {% set current = state_attr(h, 'temperature') | float(0) %}
      {% if target_temp != none and current != target_temp %}
        {% set result = result + [h] %}
      {% endif %}
    {% endfor %}
    {{ result }}

condition:
  - condition: template
    value_template: "{{ heaters_to_update | length > 0 }}"

action:
  - service: climate.set_temperature
    target:
      entity_id: "{{ heaters_to_update }}"
    data:
      temperature: "{{ target_temp }}"

  - choose: []
    default: !input extra_action
