alias: ZHA Scene Switch Handler (up to 6 buttons) v1.0 no blueprint
description: Handle ZHA scene switch button presses without blueprint
mode: restart

trigger:
  - platform: event
    event_type: zha_event

variables:
  target_device_id: "{{ states(input_target_device) if input_target_device is defined else None }}"

input_target_device:
  name: Target ZHA Device (device_id)
  description: 'Entity ID of the ZHA device (e.g. sensor.my_switch)'
  selector:
    entity:
      domain: sensor

input_button1_short_action:
  name: Button 1 Short Press Action
  default: []
  selector:
    action: {}

input_button1_long_action:
  name: Button 1 Long Press Action
  default: []
  selector:
    action: {}

input_button1_double_action:
  name: Button 1 Double Press Action
  default: []
  selector:
    action: {}

# (Аналогично input_button2_short_action, input_button2_long_action, input_button2_double_action, ... input_button6_double_action)

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == states(input_target_device) }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input input_button1_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == states(input_target_device) }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input input_button1_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == states(input_target_device) }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input input_button1_double_action

      # Добавить для кнопок 2-6 аналогично...
