blueprint:
  name: ZHA Scene Switch Handler (up to 6 buttons, device_id check) v3.4
  description: >
    Handle ZHA scene switch button presses (up to 6 buttons).
    Each button supports short_press, long_press, and double_press events with fixed commands.
    User sets actions for each button and event type.
  domain: automation
  input:
    target_device:
      name: Zigbee Scene Switch
      description: Select your ZHA scene switch
      selector:
        device:
          integration: zha

    button1_short_action:
      name: "Button 1 Short Press Action"
      default: []
      selector:
        action: {}

    button1_long_action:
      name: "Button 1 Long Press Action"
      default: []
      selector:
        action: {}

    button1_double_action:
      name: "Button 1 Double Press Action"
      default: []
      selector:
        action: {}

    button2_short_action:
      name: "Button 2 Short Press Action"
      default: []
      selector:
        action: {}

    button2_long_action:
      name: "Button 2 Long Press Action"
      default: []
      selector:
        action: {}

    button2_double_action:
      name: "Button 2 Double Press Action"
      default: []
      selector:
        action: {}

    button3_short_action:
      name: "Button 3 Short Press Action"
      default: []
      selector:
        action: {}

    button3_long_action:
      name: "Button 3 Long Press Action"
      default: []
      selector:
        action: {}

    button3_double_action:
      name: "Button 3 Double Press Action"
      default: []
      selector:
        action: {}

    button4_short_action:
      name: "Button 4 Short Press Action"
      default: []
      selector:
        action: {}

    button4_long_action:
      name: "Button 4 Long Press Action"
      default: []
      selector:
        action: {}

    button4_double_action:
      name: "Button 4 Double Press Action"
      default: []
      selector:
        action: {}

    button5_short_action:
      name: "Button 5 Short Press Action"
      default: []
      selector:
        action: {}

    button5_long_action:
      name: "Button 5 Long Press Action"
      default: []
      selector:
        action: {}

    button5_double_action:
      name: "Button 5 Double Press Action"
      default: []
      selector:
        action: {}

    button6_short_action:
      name: "Button 6 Short Press Action"
      default: []
      selector:
        action: {}

    button6_long_action:
      name: "Button 6 Long Press Action"
      default: []
      selector:
        action: {}

    button6_double_action:
      name: "Button 6 Double Press Action"
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: zha_event

condition: []

action:
  - service: persistent_notification.create
    data:
      title: "Debug ZHA Event and Blueprint Inputs"
      message: >
        blueprint defined: {{ blueprint is defined }}
        trigger defined: {{ trigger is defined }}
        trigger.event defined: {{ trigger.event is defined }}
        event.device_id: {{ trigger.event.data.device_id if trigger and trigger.event else 'N/A' }}
        blueprint.target_device_id: {{ blueprint.inputs.target_device.id if blueprint else 'N/A' }}
        event.endpoint_id: {{ trigger.event.data.endpoint_id if trigger and trigger.event else 'N/A' }}
        event.command: {{ trigger.event.data.command if trigger and trigger.event else 'N/A' }}

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button1_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button1_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button1_double_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button2_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button2_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button2_double_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button3_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button3_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button3_double_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button4_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button4_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button4_double_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button5_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button5_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button5_double_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button6_short_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button6_long_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.device_id == blueprint.inputs.target_device.id }}
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button6_double_action
