blueprint:
  name: Multi-Button Switch Scene Handler
  description: Handle up to 6 buttons on a scene-capable switch, each with custom actions.
  domain: automation
  input:
    target_device:
      name: Switch device
      description: Select your multi-button switch device
      selector:
        device: {}

    # Buttons 1–6 definitions
    button_1_event:
      name: Button 1 Event
      description: Event type for button 1 (e.g. short_press, double_press, hold)
      default: short_press
      selector:
        text: {}
    button_1_action:
      name: Button 1 Action
      description: Action to perform when Button 1 Event occurs
      default: []
      selector:
        action: {}

    button_2_event:
      name: Button 2 Event
      default: short_press
      selector:
        text: {}
    button_2_action:
      name: Button 2 Action
      default: []
      selector:
        action: {}

    button_3_event:
      name: Button 3 Event
      default: short_press
      selector:
        text: {}
    button_3_action:
      name: Button 3 Action
      default: []
      selector:
        action: {}

    button_4_event:
      name: Button 4 Event
      default: short_press
      selector:
        text: {}
    button_4_action:
      name: Button 4 Action
      default: []
      selector:
        action: {}

    button_5_event:
      name: Button 5 Event
      default: short_press
      selector:
        text: {}
    button_5_action:
      name: Button 5 Action
      default: []
      selector:
        action: {}

    button_6_event:
      name: Button 6 Event
      default: short_press
      selector:
        text: {}
    button_6_action:
      name: Button 6 Action
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input target_device

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.command == (inputs.button_1_event | default('')) }}
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 }}
        sequence: !input button_1_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.command == (inputs.button_2_event | default('')) }}
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 }}
        sequence: !input button_2_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.command == (inputs.button_3_event | default('')) }}
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 3 }}
        sequence: !input button_3_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.command == (inputs.button_4_event | default('')) }}
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 4 }}
        sequence: !input button_4_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.command == (inputs.button_5_event | default('')) }}
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 5 }}
        sequence: !input button_5_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.command == (inputs.button_6_event | default('')) }}
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 6 }}
        sequence: !input button_6_action
