blueprint:
  name: Zigbee Button Event Handler
  description: Handle ZHA button press events for any Zigbee device
  domain: automation
  input:
    device:
      name: Zigbee Device
      description: Select the Zigbee device to listen for events
      selector:
        device:
          integration: zha
    endpoint_id:
      name: Endpoint ID
      description: Endpoint number of the button (e.g., 1 or 2)
      default: 1
      selector:
        number:
          min: 1
          max: 10
    command:
      name: Command
      description: ZHA command to listen for
      default: remote_button_short_press
      selector:
        text:
    action:
      name: Action to perform
      description: Automation actions to perform on button press
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device
      endpoint_id: !input endpoint_id
      command: !input command

action: !input action
