blueprint:
  name: Zigbee Multi-Button Event Handler (up to 6 buttons) v1.0
  description: Handle multiple ZHA button press events per device with separate actions, up to 6 buttons
  domain: automation
  input:
    device:
      name: Zigbee Device
      description: Select the Zigbee device to listen for events
      selector:
        device:
          integration: zha
    buttons:
      name: Buttons Configuration
      description: List of buttons with endpoints, commands and actions
      selector:
        object:
          multiple: true

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {% set dev = trigger.event.data.device_id %}
      {% set ep = trigger.event.data.endpoint_id %}
      {% set cmd = trigger.event.data.command %}
      {% if dev != device.id %}
        {{ false }}
      {% else %}
        {% for btn in buttons %}
          {% if btn.endpoint_id == ep %}
            {% for c in btn.commands %}
              {% if c.command == cmd %}
                {{ true }}
              {% endif %}
            {% endfor %}
          {% endif %}
        {% endfor %}
      {% endif %}

action:
  - variables:
      ep: "{{ trigger.event.data.endpoint_id }}"
      cmd: "{{ trigger.event.data.command }}"
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set ep = ep %}
              {% set cmd = cmd %}
              {% set found = false %}
              {% for btn in buttons %}
                {% if btn.endpoint_id == ep %}
                  {% for c in btn.commands %}
                    {% if c.command == cmd %}
                      {% set found = c.action %}
                    {% endif %}
                  {% endfor %}
                {% endif %}
              {% endfor %}
              {{ found is not none }}
        sequence:
          - variables:
              action_to_run: >
                {% set ep = ep %}
                {% set cmd = cmd %}
                {% for btn in buttons %}
                  {% if btn.endpoint_id == ep %}
                    {% for c in btn.commands %}
                      {% if c.command == cmd %}
                        {{ c.action }}
                      {% endif %}
                    {% endfor %}
                  {% endif %}
                {% endfor %}
          - "{{ action_to_run }}"
