blueprint:
  name: ZHA Scene Switch Handler (up to 6 buttons, fixed commands) v3.2
  description: >
    Handle ZHA scene switch button presses (up to 6 buttons).
    Each button supports short_press, long_press, and double_press events with fixed command names.
    User configures only actions for each event per button, grouped by button section.
  domain: automation
  input:
    target_device:
      name: Zigbee Scene Switch
      description: Select your ZHA scene switch
      selector:
        device:
          integration: zha

    button1_section:
      name: "Button 1"
      default: {}
      selector:
        object: {}

    button1_short_action:
      name: "Short Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 1 short press

    button1_long_action:
      name: "Long Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 1 long press

    button1_double_action:
      name: "Double Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 1 double press

    button2_section:
      name: "Button 2"
      default: {}
      selector:
        object: {}

    button2_short_action:
      name: "Short Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 2 short press

    button2_long_action:
      name: "Long Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 2 long press

    button2_double_action:
      name: "Double Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 2 double press

    button3_section:
      name: "Button 3"
      default: {}
      selector:
        object: {}

    button3_short_action:
      name: "Short Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 3 short press

    button3_long_action:
      name: "Long Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 3 long press

    button3_double_action:
      name: "Double Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 3 double press

    button4_section:
      name: "Button 4"
      default: {}
      selector:
        object: {}

    button4_short_action:
      name: "Short Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 4 short press

    button4_long_action:
      name: "Long Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 4 long press

    button4_double_action:
      name: "Double Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 4 double press

    button5_section:
      name: "Button 5"
      default: {}
      selector:
        object: {}

    button5_short_action:
      name: "Short Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 5 short press

    button5_long_action:
      name: "Long Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 5 long press

    button5_double_action:
      name: "Double Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 5 double press

    button6_section:
      name: "Button 6"
      default: {}
      selector:
        object: {}

    button6_short_action:
      name: "Short Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 6 short press

    button6_long_action:
      name: "Long Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 6 long press

    button6_double_action:
      name: "Double Press Action"
      default: []
      selector:
        action: {}
      description: Action to execute on Button 6 double press

mode: restart

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {% set event_ieee = trigger.event.data.device_ieee | replace(":", "") | lower %}
      {% set device_ieee = state_attr(blueprint.inputs.target_device.entity_id, 'ieee') | replace(":", "") | lower %}
      {{ event_ieee == device_ieee }}

action:
  - service: persistent_notification.create
    data:
      title: "Debug ZHA Event and Blueprint Inputs"
      message: >
        blueprint defined: {{ blueprint is defined }}
        trigger defined: {{ trigger is defined }}
        trigger.event defined: {{ trigger.event is defined }}
        event.device_ieee raw: {{ trigger.event.data.device_ieee if trigger and trigger.event else 'N/A' }}
        event.device_ieee normalized: {{ trigger.event.data.device_ieee | replace(":", "") | lower if trigger and trigger.event else 'N/A' }}
        blueprint.ieee raw: {{ state_attr(blueprint.inputs.target_device.entity_id, 'ieee') if blueprint else 'N/A' }}
        blueprint.ieee normalized: {{ state_attr(blueprint.inputs.target_device.entity_id, 'ieee') | replace(":", "") | lower if blueprint else 'N/A' }}
        event.endpoint_id: {{ trigger.event.data.endpoint_id if trigger and trigger.event else 'N/A' }}
        event.command: {{ trigger.event.data.command if trigger and trigger.event else 'N/A' }}

  - choose:
      # Button 1
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button1_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button1_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button1_double_action

      # Button 2
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button2_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button2_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button2_double_action

      # Button 3
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button3_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button3_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button3_double_action

      # Button 4
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button4_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button4_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button4_double_action

      # Button 5
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button5_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button5_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button5_double_action

      # Button 6
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button6_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button6_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button6_double_action
