blueprint:
  name: ZHA Scene Switch Handler (up to 6 buttons, variables) v3.8
  description: >
    Handle ZHA scene switch button presses (up to 6 buttons).
    Each button supports short_press, long_press, and double_press events with fixed commands.
    User sets actions for each button and event type.
  domain: automation
  input:
    target_device:
      name: Zigbee Scene Switch
      description: Select your ZHA scene switch
      selector:
        device:
          integration: zha

    button1_short_action:
      name: Button 1 Short Press Action
      default: []
      selector:
        action: {}

    button1_long_action:
      name: Button 1 Long Press Action
      default: []
      selector:
        action: {}

    button1_double_action:
      name: Button 1 Double Press Action
      default: []
      selector:
        action: {}

    # Аналогично для кнопок 2-6 (пропущено для краткости)...

mode: restart

variables:
  target_device: !input target_device
  # Можно добавить и другие переменные, если нужно

trigger:
  - platform: event
    event_type: zha_event

condition: []

action:
  - service: persistent_notification.create
    data:
      title: "Debug Blueprint Input"
      message: >
        target_device id: {{ target_device.id }}
        target_device ieee: {{ state_attr(target_device.entity_id, 'ieee') }}
        event device_id: {{ trigger.event.data.device_id }}
        event endpoint_id: {{ trigger.event.data.endpoint_id }}
        event command: {{ trigger.event.data.command }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.device_id == target_device.id }}"
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button1_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.device_id == target_device.id }}"
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button1_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.device_id == target_device.id }}"
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button1_double_action

      # Добавь остальные кнопки аналогично
