blueprint:
  name: ZHA Scene Switch Handler (up to 6 buttons, fixed commands) v3.0
  description: >
    Handle ZHA scene switch button presses (up to 6 buttons).
    Each button supports short_press, long_press, and double_press events with fixed command names.
    User configures only actions for each event per button.
  domain: automation
  input:
    target_device:
      name: Zigbee Scene Switch
      description: Select your ZHA scene switch
      selector:
        device:
          integration: zha

    # Button 1 actions
    button1_short_action:
      name: Button 1 Short Press Action
      default: []
      selector:
        action: {}
    button1_long_action:
      name: Button 1 Long Press Action
      default: []
      selector:
        action: {}
    button1_double_action:
      name: Button 1 Double Press Action
      default: []
      selector:
        action: {}

    # Button 2 actions
    button2_short_action:
      name: Button 2 Short Press Action
      default: []
      selector:
        action: {}
    button2_long_action:
      name: Button 2 Long Press Action
      default: []
      selector:
        action: {}
    button2_double_action:
      name: Button 2 Double Press Action
      default: []
      selector:
        action: {}

    # Button 3 actions
    button3_short_action:
      name: Button 3 Short Press Action
      default: []
      selector:
        action: {}
    button3_long_action:
      name: Button 3 Long Press Action
      default: []
      selector:
        action: {}
    button3_double_action:
      name: Button 3 Double Press Action
      default: []
      selector:
        action: {}

    # Button 4 actions
    button4_short_action:
      name: Button 4 Short Press Action
      default: []
      selector:
        action: {}
    button4_long_action:
      name: Button 4 Long Press Action
      default: []
      selector:
        action: {}
    button4_double_action:
      name: Button 4 Double Press Action
      default: []
      selector:
        action: {}

    # Button 5 actions
    button5_short_action:
      name: Button 5 Short Press Action
      default: []
      selector:
        action: {}
    button5_long_action:
      name: Button 5 Long Press Action
      default: []
      selector:
        action: {}
    button5_double_action:
      name: Button 5 Double Press Action
      default: []
      selector:
        action: {}

    # Button 6 actions
    button6_short_action:
      name: Button 6 Short Press Action
      default: []
      selector:
        action: {}
    button6_long_action:
      name: Button 6 Long Press Action
      default: []
      selector:
        action: {}
    button6_double_action:
      name: Button 6 Double Press Action
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {% set event_ieee = trigger.event.data.device_ieee | replace(":", "") | lower %}
      {% set device_ieee = state_attr(blueprint.inputs.target_device.entity_id, 'ieee') | replace(":", "") | lower %}
      {{ event_ieee == device_ieee }}

action:
  - service: persistent_notification.create
    data:
      title: "Debug ZHA Event and Device Attributes"
      message: >
        event.device_ieee raw: {{ trigger.event.data.device_ieee | string }}
        event.device_ieee normalized: {{ trigger.event.data.device_ieee | replace(":", "") | lower }}
        blueprint.ieee raw: {{ state_attr(blueprint.inputs.target_device.entity_id, 'ieee') | string }}
        blueprint.ieee normalized: {{ state_attr(blueprint.inputs.target_device.entity_id, 'ieee') | replace(":", "") | lower }}
        endpoint_id: {{ trigger.event.data.endpoint_id | string }}
        cluster_id: {{ trigger.event.data.cluster_id | string }}
        command: {{ trigger.event.data.command | string }}
        args: {{ trigger.event.data.args | string }}

  - choose:
      # Button 1
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button1_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button1_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button1_double_action

      # Button 2
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button2_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button2_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button2_double_action

      # Button 3
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button3_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button3_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button3_double_action

      # Button 4
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button4_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button4_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button4_double_action

      # Button 5
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button5_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button5_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button5_double_action

      # Button 6
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == 'remote_button_short_press' }}"
        sequence: !input button6_short_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: !input button6_long_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: !input button6_double_action
