blueprint:
  name: ZHA Scene Switch Handler (up to 6 buttons)
  description: Handle ZHA scene switch button presses (supports up to 6 buttons with multiple press types)
  domain: automation
  input:
    target_device:
      name: Zigbee Scene Switch
      description: Select your ZHA scene switch
      selector:
        device:
          integration: zha

    # Inputs for each button
    button1_command:
      name: Button 1 Command
      description: Select press type for Button 1
      default: remote_button_short_press
      selector:
        select:
          options:
            - remote_button_short_press
            - remote_button_long_press
            - remote_button_double_press
    button1_action:
      name: Button 1 Action
      description: Action to run when Button 1 is pressed
      default: []
      selector:
        action: {}

    button2_command:
      name: Button 2 Command
      default: remote_button_short_press
      selector:
        select:
          options:
            - remote_button_short_press
            - remote_button_long_press
            - remote_button_double_press
    button2_action:
      name: Button 2 Action
      default: []
      selector:
        action: {}

    button3_command:
      name: Button 3 Command
      default: remote_button_short_press
      selector:
        select:
          options:
            - remote_button_short_press
            - remote_button_long_press
            - remote_button_double_press
    button3_action:
      name: Button 3 Action
      default: []
      selector:
        action: {}

    button4_command:
      name: Button 4 Command
      default: remote_button_short_press
      selector:
        select:
          options:
            - remote_button_short_press
            - remote_button_long_press
            - remote_button_double_press
    button4_action:
      name: Button 4 Action
      default: []
      selector:
        action: {}

    button5_command:
      name: Button 5 Command
      default: remote_button_short_press
      selector:
        select:
          options:
            - remote_button_short_press
            - remote_button_long_press
            - remote_button_double_press
    button5_action:
      name: Button 5 Action
      default: []
      selector:
        action: {}

    button6_command:
      name: Button 6 Command
      default: remote_button_short_press
      selector:
        select:
          options:
            - remote_button_short_press
            - remote_button_long_press
            - remote_button_double_press
    button6_action:
      name: Button 6 Action
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id == (device_id := inputs.target_device) }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == inputs.button1_command }}
        sequence: !input button1_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == inputs.button2_command }}
        sequence: !input button2_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 3 and trigger.event.data.command == inputs.button3_command }}
        sequence: !input button3_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 4 and trigger.event.data.command == inputs.button4_command }}
        sequence: !input button4_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 5 and trigger.event.data.command == inputs.button5_command }}
        sequence: !input button5_action

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 6 and trigger.event.data.command == inputs.button6_command }}
        sequence: !input button6_action
